# Modo online (Supabase): rankings opcionales
T = {
"Rankings online (opcional)": ("Online rankings (optional)", "Rankings online (opcional)", "Classements en ligne (facultatif)", "Classifiche online (facoltativo)", "Online-Ranglisten (optional)"),
"Si activás «Participar en los rankings online» (viene apagado), el juego crea un usuario anónimo, sin correo ni contraseña, y envía a nuestro servidor (Supabase) tu nombre de piloto y tus mejores marcas (tiempo o puntos, pista y auto) para armar el ranking, que ven todos los jugadores. No se envía ningún otro dato, y lo podés apagar cuando quieras. Para borrar tus marcas escribí al contacto del juego.": (
	"If you turn on “Take part in online rankings” (it is off by default), the game creates an anonymous user, with no email or password, and sends your driver name and your best marks (time or points, track and car) to our server (Supabase) to build the ranking, which all players can see. No other data is sent, and you can turn it off at any time. To delete your marks, write to the game's contact.",
	"Se você ativar «Participar dos rankings online» (vem desligado), o jogo cria um usuário anônimo, sem e-mail nem senha, e envia ao nosso servidor (Supabase) o nome de piloto e suas melhores marcas (tempo ou pontos, pista e carro) para montar o ranking, que todos os jogadores veem. Nenhum outro dado é enviado, e você pode desligar quando quiser. Para apagar suas marcas, escreva para o contato do jogo.",
	"Si vous activez « Participer aux classements en ligne » (désactivé par défaut), le jeu crée un utilisateur anonyme, sans e-mail ni mot de passe, et envoie à notre serveur (Supabase) votre nom de pilote et vos meilleures marques (temps ou points, piste et voiture) pour établir le classement, que tous les joueurs voient. Aucune autre donnée n'est envoyée, et vous pouvez le désactiver à tout moment. Pour supprimer vos marques, écrivez au contact du jeu.",
	"Se attivi «Partecipa alle classifiche online» (è disattivato di default), il gioco crea un utente anonimo, senza e-mail né password, e invia al nostro server (Supabase) il tuo nome da pilota e i tuoi migliori risultati (tempo o punti, pista e auto) per creare la classifica, che tutti i giocatori vedono. Non viene inviato nessun altro dato e puoi disattivarlo quando vuoi. Per cancellare i tuoi risultati scrivi al contatto del gioco.",
	"Wenn du „An den Online-Ranglisten teilnehmen“ aktivierst (standardmäßig aus), erstellt das Spiel einen anonymen Nutzer ohne E-Mail und Passwort und sendet deinen Fahrernamen und deine Bestwerte (Zeit oder Punkte, Strecke und Auto) an unseren Server (Supabase), um die Rangliste zu erstellen, die alle Spieler sehen. Es werden keine weiteren Daten gesendet, und du kannst es jederzeit ausschalten. Zum Löschen deiner Werte schreibe an den Kontakt des Spiels."),
"Rankings online: se envían tu nombre de piloto y tus mejores marcas (tiempo y puntos) sin crear ninguna cuenta. No se envía nada más.": (
	"Online rankings: your driver name and best marks (time and points) are sent without creating any account. Nothing else is sent.",
	"Rankings online: são enviados o seu nome de piloto e suas melhores marcas (tempo e pontos) sem criar nenhuma conta. Nada mais é enviado.",
	"Classements en ligne : votre nom de pilote et vos meilleures marques (temps et points) sont envoyés sans créer de compte. Rien d'autre n'est envoyé.",
	"Classifiche online: vengono inviati il tuo nome da pilota e i tuoi migliori risultati (tempo e punti) senza creare nessun account. Non viene inviato altro.",
	"Online-Ranglisten: Dein Fahrername und deine Bestwerte (Zeit und Punkte) werden ohne Konto gesendet. Es wird nichts anderes gesendet."),
"Participar en los rankings online": ("Take part in online rankings", "Participar dos rankings online", "Participer aux classements en ligne", "Partecipa alle classifiche online", "An den Online-Ranglisten teilnehmen"),
"Probando…": ("Testing…", "Testando…", "Test en cours…", "Prova in corso…", "Test läuft …"),
}
