# Revisión de privacidad y términos: contacto, datos online, cuenta y rankings
T = {
"Contacto": ("Contact", "Contato", "Contact", "Contatto", "Kontakt"),
"Dudas o pedidos sobre tus datos o tu cuenta: roldanhr98@gmail.com (SRGamestudios).": (
	"Questions or requests about your data or account: roldanhr98@gmail.com (SRGamestudios).",
	"Dúvidas ou pedidos sobre seus dados ou sua conta: roldanhr98@gmail.com (SRGamestudios).",
	"Questions ou demandes sur vos données ou votre compte : roldanhr98@gmail.com (SRGamestudios).",
	"Dubbi o richieste sui tuoi dati o sul tuo account: roldanhr98@gmail.com (SRGamestudios).",
	"Fragen oder Anliegen zu deinen Daten oder deinem Konto: roldanhr98@gmail.com (SRGamestudios)."),
"Tu perfil de juego (autos, mejoras, pintura, dinero del juego, estrellas, tiempos y opciones) queda en el almacenamiento privado de la app, en tu teléfono. Solo si participás en el modo online se envían tu nombre de piloto y tus mejores marcas, y tu correo si creás una cuenta. Si desinstalás la app, se pierde lo que está en el teléfono.": (
	"Your game profile (cars, upgrades, paint, in-game money, stars, times and options) stays in the app's private storage, on your phone. Only if you take part in online mode are your driver name and best marks sent, and your email if you create an account. If you uninstall the app, what is on the phone is lost.",
	"Seu perfil de jogo (carros, melhorias, pintura, dinheiro do jogo, estrelas, tempos e opções) fica no armazenamento privado do app, no seu celular. Só se você participar do modo online são enviados seu nome de piloto e suas melhores marcas, e seu e-mail se criar uma conta. Se você desinstalar o app, o que está no celular é perdido.",
	"Votre profil de jeu (voitures, améliorations, peinture, argent du jeu, étoiles, temps et options) reste dans le stockage privé de l'application, sur votre téléphone. Seulement si vous participez au mode en ligne, votre nom de pilote et vos meilleures marques sont envoyés, ainsi que votre e-mail si vous créez un compte. Si vous désinstallez l'application, ce qui est sur le téléphone est perdu.",
	"Il tuo profilo di gioco (auto, miglioramenti, vernice, denaro del gioco, stelle, tempi e opzioni) resta nell'archivio privato dell'app, sul tuo telefono. Solo se partecipi alla modalità online vengono inviati il tuo nome da pilota e i tuoi migliori risultati, e la tua e-mail se crei un account. Se disinstalli l'app, ciò che è sul telefono va perso.",
	"Dein Spielprofil (Autos, Verbesserungen, Lackierung, Spielgeld, Sterne, Zeiten und Optionen) bleibt im privaten Speicher der App auf deinem Handy. Nur wenn du am Online-Modus teilnimmst, werden dein Fahrername und deine Bestwerte gesendet, und deine E-Mail, wenn du ein Konto erstellst. Wenn du die App deinstallierst, geht verloren, was auf dem Handy ist."),
"El juego funciona sin conexión. Se usa internet para las compras (a través de Google Play), para descargar contenido en la versión de prueba y, solo si participás, para el modo online (rankings y cuenta).": (
	"The game works offline. The internet is used for purchases (through Google Play), to download content in the test version and, only if you take part, for online mode (rankings and account).",
	"O jogo funciona sem conexão. A internet é usada para as compras (pelo Google Play), para baixar conteúdo na versão de teste e, só se você participar, para o modo online (rankings e conta).",
	"Le jeu fonctionne hors ligne. Internet sert aux achats (via Google Play), à télécharger du contenu dans la version de test et, seulement si vous participez, au mode en ligne (classements et compte).",
	"Il gioco funziona senza connessione. Internet serve per gli acquisti (tramite Google Play), per scaricare contenuti nella versione di prova e, solo se partecipi, per la modalità online (classifiche e account).",
	"Das Spiel funktioniert ohne Verbindung. Das Internet wird für Käufe (über Google Play), zum Herunterladen von Inhalten in der Testversion und, nur wenn du teilnimmst, für den Online-Modus (Ranglisten und Konto) genutzt."),
"Dónde se guardan los datos online": ("Where online data is stored", "Onde ficam os dados online", "Où sont stockées les données en ligne", "Dove sono salvati i dati online", "Wo die Online-Daten gespeichert werden"),
"Los datos del modo online (nombre de piloto, marcas y, si creás una cuenta, tu correo) se guardan en servidores de Supabase, que los procesa por nuestra cuenta. Los conservamos hasta que borres tu cuenta o nos pidas borrarlos. Los registros técnicos de envíos solo sirven para frenar abusos.": (
	"Online-mode data (driver name, marks and, if you create an account, your email) is stored on Supabase servers, which process it on our behalf. We keep it until you delete your account or ask us to delete it. Technical submission logs are only used to stop abuse.",
	"Os dados do modo online (nome de piloto, marcas e, se criar uma conta, seu e-mail) ficam em servidores da Supabase, que os processa em nosso nome. Guardamos até você apagar sua conta ou pedir que apaguemos. Os registros técnicos de envios servem só para frear abusos.",
	"Les données du mode en ligne (nom de pilote, marques et, si vous créez un compte, votre e-mail) sont stockées sur des serveurs de Supabase, qui les traite pour notre compte. Nous les conservons jusqu'à ce que vous supprimiez votre compte ou nous demandiez de les supprimer. Les journaux techniques d'envoi servent seulement à freiner les abus.",
	"I dati della modalità online (nome da pilota, risultati e, se crei un account, la tua e-mail) sono salvati su server di Supabase, che li tratta per nostro conto. Li conserviamo finché non cancelli il tuo account o ci chiedi di cancellarli. I registri tecnici degli invii servono solo a frenare gli abusi.",
	"Die Daten des Online-Modus (Fahrername, Werte und, wenn du ein Konto erstellst, deine E-Mail) werden auf Servern von Supabase gespeichert, das sie in unserem Auftrag verarbeitet. Wir behalten sie, bis du dein Konto löschst oder uns um Löschung bittest. Die technischen Sendeprotokolle dienen nur dazu, Missbrauch zu verhindern."),
"Cuenta y rankings online": ("Online account and rankings", "Conta e rankings online", "Compte et classements en ligne", "Account e classifiche online", "Online-Konto und Ranglisten"),
"Si usás el modo online, tu nombre de piloto y tus mejores marcas se muestran a otros jugadores. Elegí un nombre que no sea ofensivo ni se haga pasar por otra persona: podemos cambiarlo, o quitar marcas conseguidas con trampas o programas externos. La cuenta con correo es personal y solo para mayores de 13 años: cuidá tu contraseña. Podés borrar tu cuenta cuando quieras desde el juego. El servicio online puede cambiar o detenerse, y no afecta lo que jugás sin conexión.": (
	"If you use online mode, your driver name and best marks are shown to other players. Pick a name that is not offensive and does not impersonate anyone: we may change it, or remove marks obtained by cheating or with external tools. The email account is personal and only for people aged 13 or older: keep your password safe. You can delete your account at any time from the game. The online service may change or stop, and does not affect what you play offline.",
	"Se você usar o modo online, seu nome de piloto e suas melhores marcas são mostrados a outros jogadores. Escolha um nome que não seja ofensivo nem se passe por outra pessoa: podemos mudá-lo ou remover marcas conseguidas com trapaças ou programas externos. A conta com e-mail é pessoal e só para maiores de 13 anos: cuide da sua senha. Você pode apagar sua conta quando quiser dentro do jogo. O serviço online pode mudar ou parar, e não afeta o que você joga sem conexão.",
	"Si vous utilisez le mode en ligne, votre nom de pilote et vos meilleures marques sont montrés aux autres joueurs. Choisissez un nom qui ne soit pas offensant et n'usurpe personne : nous pouvons le changer ou retirer les marques obtenues par triche ou avec des programmes externes. Le compte e-mail est personnel et réservé aux personnes de 13 ans ou plus : protégez votre mot de passe. Vous pouvez supprimer votre compte à tout moment depuis le jeu. Le service en ligne peut changer ou s'arrêter, et n'affecte pas ce que vous jouez hors ligne.",
	"Se usi la modalità online, il tuo nome da pilota e i tuoi migliori risultati vengono mostrati agli altri giocatori. Scegli un nome non offensivo che non si spacci per un'altra persona: possiamo cambiarlo o rimuovere risultati ottenuti con trucchi o programmi esterni. L'account e-mail è personale e solo per chi ha almeno 13 anni: proteggi la tua password. Puoi cancellare il tuo account quando vuoi dal gioco. Il servizio online può cambiare o fermarsi e non influisce su ciò che giochi offline.",
	"Wenn du den Online-Modus nutzt, werden dein Fahrername und deine Bestwerte anderen Spielern angezeigt. Wähle einen Namen, der nicht beleidigend ist und sich nicht als andere Person ausgibt: Wir können ihn ändern oder Werte entfernen, die durch Betrug oder externe Programme erzielt wurden. Das E-Mail-Konto ist persönlich und nur für Personen ab 13 Jahren: Schütze dein Passwort. Du kannst dein Konto jederzeit im Spiel löschen. Der Online-Dienst kann sich ändern oder eingestellt werden und betrifft nicht, was du offline spielst."),
"El dinero, los autos, las estrellas y los logros son virtuales: no tienen valor real, no se canjean por dinero ni se venden.": ("In-game money, cars, stars and achievements are virtual: they have no real value and cannot be exchanged for money or sold.", "O dinheiro, os carros, as estrelas e as conquistas são virtuais: não têm valor real e não são trocados por dinheiro nem vendidos.", "L'argent, les voitures, les étoiles et les succès sont virtuels : ils n'ont aucune valeur réelle et ne s'échangent ni ne se vendent contre de l'argent.", "Il denaro, le auto, le stelle e gli obiettivi sono virtuali: non hanno valore reale e non si scambiano con denaro né si vendono.", "Geld, Autos, Sterne und Erfolge im Spiel sind virtuell: Sie haben keinen echten Wert und können weder gegen Geld getauscht noch verkauft werden."),
"Mapa fantasía suelto: una vuelta inmensa entre flores gigantes, con subida, bajada y un rival a tu ritmo. No pertenece a ninguna copa.": ("Standalone fantasy map: one huge lap among giant flowers, with a climb, a descent and a rival at your pace. It is not part of any cup.", "Mapa de fantasia avulso: uma volta imensa entre flores gigantes, com subida, descida e um rival no seu ritmo. Não faz parte de nenhuma copa.", "Carte fantaisie indépendante : un tour immense parmi des fleurs géantes, avec une montée, une descente et un rival à votre rythme. Elle ne fait partie d'aucune coupe.", "Mappa fantasy a sé: un giro immenso tra fiori giganti, con salita, discesa e un rivale al tuo ritmo. Non fa parte di nessuna coppa.", "Eigenständige Fantasy-Karte: eine riesige Runde zwischen Riesenblumen, mit Anstieg, Gefälle und einem Rivalen in deinem Tempo. Sie gehört zu keinem Pokal."),
}
