# Mapas fantasía: sección del menú y los mapas planetarios
T = {
"MAPAS FANTASÍA": ("FANTASY MAPS", "MAPAS DE FANTASIA", "CARTES FANTASY", "MAPPE FANTASY", "FANTASY-KARTEN"),
"FANTASÍA": ("FANTASY", "FANTASIA", "FANTASY", "FANTASY", "FANTASY"),
"mapas de ensueño": ("dream maps", "mapas de sonho", "cartes de rêve", "mappe da sogno", "Traumkarten"),
"Mapas sueltos de mundos imposibles, todos hechos en papel. Sin copas ni estrellas: correlos cuando quieras.": (
	"Standalone maps from impossible worlds, all made of paper. No cups or stars: race them whenever you like.",
	"Mapas avulsos de mundos impossíveis, todos feitos de papel. Sem copas nem estrelas: corra quando quiser.",
	"Des cartes indépendantes de mondes impossibles, toutes en papier. Pas de coupes ni d'étoiles : courez-y quand vous voulez.",
	"Mappe a sé di mondi impossibili, tutte di carta. Niente coppe né stelle: corri quando vuoi.",
	"Eigenständige Karten aus unmöglichen Welten, alle aus Papier. Keine Pokale oder Sterne: Fahr sie, wann du willst."),
"Los rivales te siguen el ritmo. No pertenece a ninguna copa.": ("The rivals keep up with your pace. It is not part of any cup.", "Os rivais acompanham o seu ritmo. Não faz parte de nenhuma copa.", "Les rivaux suivent votre rythme. Elle ne fait partie d'aucune coupe.", "I rivali tengono il tuo ritmo. Non fa parte di nessuna coppa.", "Die Rivalen halten dein Tempo. Sie gehört zu keinem Pokal."),
"Marte · Monte Olimpo": ("Mars · Olympus Mons", "Marte · Monte Olimpo", "Mars · Mont Olympe", "Marte · Monte Olimpo", "Mars · Olympus Mons"),
"La Luna · Mar de la Tranquilidad": ("The Moon · Sea of Tranquility", "A Lua · Mar da Tranquilidade", "La Lune · Mer de la Tranquillité", "La Luna · Mare della Tranquillità", "Der Mond · Meer der Ruhe"),
"Anillo de Júpiter": ("Jupiter's Ring", "Anel de Júpiter", "Anneau de Jupiter", "Anello di Giove", "Jupiterring"),
"Flores gigantes, un planeta enorme y un agujero negro debajo.": ("Giant flowers, a huge planet and a black hole below.", "Flores gigantes, um planeta enorme e um buraco negro embaixo.", "Des fleurs géantes, une planète énorme et un trou noir en dessous.", "Fiori giganti, un pianeta enorme e un buco nero sotto.", "Riesenblumen, ein riesiger Planet und ein Schwarzes Loch darunter."),
"Un volcán rojo: subida de 300 m, la caldera y un cañón.": ("A red volcano: a 300 m climb, the caldera and a canyon.", "Um vulcão vermelho: subida de 300 m, a caldeira e um cânion.", "Un volcan rouge : une montée de 300 m, la caldeira et un canyon.", "Un vulcano rosso: salita di 300 m, la caldera e un canyon.", "Ein roter Vulkan: 300 m Anstieg, die Caldera und ein Canyon."),
"Cráteres, la Tierra en el cielo y un módulo lunar.": ("Craters, the Earth in the sky and a lunar module.", "Crateras, a Terra no céu e um módulo lunar.", "Des cratères, la Terre dans le ciel et un module lunaire.", "Crateri, la Terra nel cielo e un modulo lunare.", "Krater, die Erde am Himmel und eine Mondlandefähre."),
"Cristales de hielo flotando frente a un Júpiter gigante.": ("Ice crystals floating in front of a giant Jupiter.", "Cristais de gelo flutuando diante de um Júpiter gigante.", "Des cristaux de glace flottant devant un Jupiter géant.", "Cristalli di ghiaccio che fluttuano davanti a un Giove gigante.", "Eiskristalle, die vor einem riesigen Jupiter schweben."),
"Ley aplicable": ("Governing law", "Lei aplicável", "Droit applicable", "Legge applicabile", "Anwendbares Recht"),
"Tus derechos": ("Your rights", "Seus direitos", "Vos droits", "I tuoi diritti", "Deine Rechte"),
"Estas condiciones se rigen por las leyes de la República Argentina. Si sos consumidor, esto no limita los derechos que te reconozca la ley de tu país.": (
	"These terms are governed by the laws of the Argentine Republic. If you are a consumer, this does not limit the rights your own country's law grants you.",
	"Estas condições são regidas pelas leis da República Argentina. Se você é consumidor, isso não limita os direitos que a lei do seu país lhe reconheça.",
	"Ces conditions sont régies par les lois de la République argentine. Si vous êtes consommateur, cela ne limite pas les droits que la loi de votre pays vous reconnaît.",
	"Queste condizioni sono regolate dalle leggi della Repubblica Argentina. Se sei un consumatore, ciò non limita i diritti che la legge del tuo paese ti riconosce.",
	"Diese Bedingungen unterliegen den Gesetzen der Argentinischen Republik. Wenn du Verbraucher bist, schränkt dies die Rechte, die dir das Recht deines Landes gewährt, nicht ein."),
"El responsable es SRGamestudios (Argentina). Podés pedir acceso, corrección o borrado de tus datos escribiendo al contacto, o borrar tu cuenta desde el juego. En Argentina, la Agencia de Acceso a la Información Pública (AAIP), órgano de control de la Ley 25.326, atiende las denuncias y reclamos. Si estás en otro país, también podés ejercer los derechos que te reconozca tu ley local.": (
	"The controller is SRGamestudios (Argentina). You can ask for access, correction or deletion of your data by writing to the contact, or delete your account from the game. In Argentina, the Agency for Access to Public Information (AAIP), the supervisory authority under Law 25,326, handles complaints and claims. If you are in another country, you can also exercise the rights your local law grants you.",
	"O responsável é a SRGamestudios (Argentina). Você pode pedir acesso, correção ou exclusão dos seus dados escrevendo para o contato, ou apagar sua conta dentro do jogo. Na Argentina, a Agência de Acesso à Informação Pública (AAIP), órgão de controle da Lei 25.326, atende denúncias e reclamações. Se você está em outro país, também pode exercer os direitos que a sua lei local lhe reconheça.",
	"Le responsable est SRGamestudios (Argentine). Vous pouvez demander l'accès, la correction ou la suppression de vos données en écrivant au contact, ou supprimer votre compte depuis le jeu. En Argentine, l'Agence d'accès à l'information publique (AAIP), autorité de contrôle de la loi 25.326, traite les plaintes et réclamations. Si vous êtes dans un autre pays, vous pouvez aussi exercer les droits que votre loi locale vous reconnaît.",
	"Il responsabile è SRGamestudios (Argentina). Puoi chiedere accesso, correzione o cancellazione dei tuoi dati scrivendo al contatto, o cancellare il tuo account dal gioco. In Argentina, l'Agenzia per l'Accesso all'Informazione Pubblica (AAIP), autorità di controllo della Legge 25.326, gestisce denunce e reclami. Se sei in un altro paese, puoi anche esercitare i diritti che la tua legge locale ti riconosce.",
	"Verantwortlicher ist SRGamestudios (Argentinien). Du kannst Auskunft, Berichtigung oder Löschung deiner Daten verlangen, indem du an den Kontakt schreibst, oder dein Konto im Spiel löschen. In Argentinien bearbeitet die Behörde für den Zugang zu öffentlichen Informationen (AAIP), die Aufsichtsbehörde nach dem Gesetz 25.326, Beschwerden und Anträge. Wenn du in einem anderen Land bist, kannst du auch die Rechte ausüben, die dir dein lokales Recht gewährt."),
}
