# Privacidad dentro del juego: chat, posición y mercado del mundo online
T = {
"Mundo online: chat, posición y mercado": ("Online world: chat, position and market", "Mundo online: chat, posição e mercado", "Monde en ligne : chat, position et marché", "Mondo online: chat, posizione e mercato", "Online-Welt: Chat, Position und Markt"),
"Si entrás al mundo abierto desde Modo online (hace falta una cuenta), el juego envía a nuestro servidor (Supabase) la posición de tu auto en el mapa del juego, tu velocidad y tu auto (cada pocos segundos, mientras estás conectado; no es la ubicación real de tu teléfono), los mensajes de chat que escribís (los insultos se tapan con asteriscos), a quién seguís y los autos que ponés a la venta. Si alguien te reporta, se guarda la evidencia (tus mensajes recientes y tus últimas posiciones y velocidades) para revisarla a mano: un reporte no castiga a nadie automáticamente. Todo se borra junto con tu cuenta.": (
"If you enter the open world from Online mode (an account is required), the game sends to our server (Supabase) your car's position on the in-game map, your speed and your car (every few seconds, while you are connected; it is not your phone's real location), the chat messages you write (insults are masked with asterisks), who you follow and the cars you list for sale. If someone reports you, the evidence (your recent messages and your latest positions and speeds) is stored to be reviewed by hand: a report never penalizes anyone automatically. Everything is deleted along with your account.",
"Se você entrar no mundo aberto pelo Modo online (é preciso ter uma conta), o jogo envia ao nosso servidor (Supabase) a posição do seu carro no mapa do jogo, a sua velocidade e o seu carro (a cada poucos segundos, enquanto você está conectado; não é a localização real do seu celular), as mensagens de chat que você escreve (os insultos são cobertos com asteriscos), quem você segue e os carros que você coloca à venda. Se alguém denunciar você, a evidência (suas mensagens recentes e suas últimas posições e velocidades) é guardada para ser revisada à mão: uma denúncia não pune ninguém automaticamente. Tudo é apagado junto com a sua conta.",
"Si tu entres dans le monde ouvert depuis le Mode en ligne (un compte est nécessaire), le jeu envoie à notre serveur (Supabase) la position de ta voiture sur la carte du jeu, ta vitesse et ta voiture (toutes les quelques secondes, pendant que tu es connecté ; ce n'est pas la position réelle de ton téléphone), les messages de chat que tu écris (les insultes sont masquées par des astérisques), les personnes que tu suis et les voitures que tu mets en vente. Si quelqu'un te signale, les preuves (tes messages récents et tes dernières positions et vitesses) sont conservées pour être examinées à la main : un signalement ne sanctionne personne automatiquement. Tout est supprimé avec ton compte.",
"Se entri nel mondo aperto dalla Modalità online (serve un account), il gioco invia al nostro server (Supabase) la posizione della tua auto sulla mappa del gioco, la tua velocità e la tua auto (ogni pochi secondi, mentre sei connesso; non è la posizione reale del tuo telefono), i messaggi di chat che scrivi (gli insulti vengono coperti con asterischi), chi segui e le auto che metti in vendita. Se qualcuno ti segnala, le prove (i tuoi messaggi recenti e le tue ultime posizioni e velocità) vengono conservate per essere esaminate a mano: una segnalazione non punisce nessuno automaticamente. Tutto viene cancellato insieme al tuo account.",
"Wenn du die offene Welt über den Online-Modus betrittst (ein Konto ist nötig), sendet das Spiel an unseren Server (Supabase) die Position deines Autos auf der Spielkarte, deine Geschwindigkeit und dein Auto (alle paar Sekunden, solange du verbunden bist; es ist nicht der echte Standort deines Handys), die Chat-Nachrichten, die du schreibst (Beleidigungen werden mit Sternchen verdeckt), wem du folgst und die Autos, die du zum Verkauf anbietest. Wenn dich jemand meldet, werden die Belege (deine letzten Nachrichten sowie deine letzten Positionen und Geschwindigkeiten) gespeichert, um von Hand geprüft zu werden: Eine Meldung bestraft niemanden automatisch. Alles wird zusammen mit deinem Konto gelöscht."),
}
