# Travesía X: convoy off-road
T = {
"convoy off-road · 20 km · barro, lago y colina": ("off-road convoy · 20 km · mud, lake and hill", "comboio off-road · 20 km · barro, lago e colina", "convoi off-road · 20 km · boue, lac et colline", "convoglio off-road · 20 km · fango, lago e collina", "Offroad-Konvoi · 20 km · Schlamm, See und Hügel"),
"Convoy off-road de 21 km: barro, pedregal, un lago para vadear, zigzag a la colina y bajada suelta. Se llega todos juntos.": ("21 km off-road convoy: mud, rocks, a lake to wade through, zigzags up the hill and a loose downhill. You all arrive together.", "Comboio off-road de 21 km: barro, pedregal, um lago para atravessar, zigue-zague na colina e descida solta. Todos chegam juntos.", "Convoi off-road de 21 km : boue, pierriers, un lac à traverser, lacets dans la colline et descente glissante. On arrive tous ensemble.", "Convoglio off-road di 21 km: fango, pietraie, un lago da guadare, tornanti sulla collina e discesa sciolta. Si arriva tutti insieme.", "21 km Offroad-Konvoi: Schlamm, Geröll, ein See zum Durchfahren, Serpentinen den Hügel hinauf und eine rutschige Abfahrt. Alle kommen zusammen an."),
"Un convoy de 5 autos y camiones va en fila: si acelerás, aceleran; si te quedás, te esperan un poco, pero si te perdés muy lejos los perdés. Hay que llegar a la meta con el grupo.": ("A convoy of 5 cars and trucks drives in single file: if you speed up, they speed up; if you fall behind they wait a little, but if you get too far you lose them. You have to reach the finish with the group.", "Um comboio de 5 carros e caminhões anda em fila: se você acelera, eles aceleram; se ficar para trás, eles esperam um pouco, mas se se afastar demais você os perde. É preciso chegar à meta com o grupo.", "Un convoi de 5 voitures et camions roule en file : si tu accélères, ils accélèrent ; si tu prends du retard, ils t'attendent un peu, mais si tu te laisses distancer trop loin tu les perds. Il faut arriver avec le groupe.", "Un convoglio di 5 auto e camion va in fila: se acceleri, accelerano; se resti indietro ti aspettano un po', ma se ti allontani troppo li perdi. Bisogna arrivare al traguardo con il gruppo.", "Ein Konvoi aus 5 Autos und Lastwagen fährt im Gänsemarsch: Gibst du Gas, fahren sie schneller; bleibst du zurück, warten sie ein wenig, aber wenn du zu weit abfällst, verlierst du sie. Du musst mit der Gruppe ins Ziel kommen."),
"¡LLEGASTE CON EL GRUPO!": ("YOU ARRIVED WITH THE GROUP!", "VOCÊ CHEGOU COM O GRUPO!", "TU ES ARRIVÉ AVEC LE GROUPE !", "SEI ARRIVATO COL GRUPPO!", "DU BIST MIT DER GRUPPE ANGEKOMMEN!"),
"PERDISTE AL CONVOY": ("YOU LOST THE CONVOY", "VOCÊ PERDEU O COMBOIO", "TU AS PERDU LE CONVOI", "HAI PERSO IL CONVOGLIO", "DU HAST DEN KONVOI VERLOREN"),
"Unión del grupo: %d %%": ("Group cohesion: %d %%", "União do grupo: %d %%", "Cohésion du groupe : %d %%", "Unione del gruppo: %d %%", "Gruppenzusammenhalt: %d %%"),
}
